### ISSUE TITLE
Problemas con los certificados y/o llave privada

### ISSUE THREAD

**Issue by rvillablanca** [TransbankDevelopers/transbank-sdk-java-patpass-example#1]
Al parecer existe un problema con el certificado, aunque no queda claro si es el certificado de transbank del comercio. Adjunto el error:
```
[INFO] Started Jetty Server
0    [qtp169110289-19] INFO  org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean  - Creating Service {http://service.wswebpay.webpay.transbank.com/}WSWebpayServiceImplService from WSDL: jar:file:/home/rodrigo/.m2/repository/com/github/transbankdevelopers/transbank-sdk-java/1.4.0/transbank-sdk-java-1.4.0.jar!/wsdl/integracion/transbank-ws-webpay-service.wsdl
2647 [qtp169110289-19] WARN  org.apache.cxf.phase.PhaseInterceptorChain  - Interceptor for {http://service.wswebpay.webpay.transbank.com/}WSWebpayServiceImplService#{http://service.wswebpay.webpay.transbank.com/}initTransaction has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: The signature or decryption was invalid
	at org.apache.cxf.ws.security.wss4j.WSS4JUtils.createSoapFault(WSS4JUtils.java:218)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:329)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:184)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:93)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:798)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1670)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1551)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1348)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	at com.sun.proxy.$Proxy56.initTransaction(Unknown Source)
	at cl.transbank.webpay.wrapper.WSWebpayServiceWrapper.initTransaction(WSWebpayServiceWrapper.java:21)
	at cl.transbank.patpass.PatPassByWebpayNormal.initTransaction(PatPassByWebpayNormal.java:61)
	at org.apache.jsp.tbk_002dpatpass_002dnormal_jsp._jspService(tbk_002dpatpass_002dnormal_jsp.java:216)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: The signature or decryption was invalid
	at org.apache.wss4j.dom.processor.SignatureProcessor.handleToken(SignatureProcessor.java:201)
	at org.apache.wss4j.dom.engine.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:344)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:280)
	... 63 more
```

Como dato adicional entiendo que el certificado de integración (ambiente test) expiró hace pocos días. Tal vez es necesario actualizar los certificados y llaves con los que están en TransbankDevelopers desde [aquí](http://www.transbankdevelopers.cl/download?file=AllCredentials.rar&name=AllCredentials.rar)

**Comment by leosoto** [comment]
Hola! En efecto el certificado de Transbank expiró el 2 de septiembre. Y al cambiar el certificado por el nuevo, dejan de funcionar las credenciales preconfiguradas (pues en integración Transbank usa diferentes certificados según la identidad del comercio). Estamos a la espera de nuevas credenciales de prueba patpass (que no las veo dentro de ese archivo .rar)

Genial que te haya interesado probar esto! Te aviso por acá cuando esté resuelto lo del certificado!

**Comment by paecasti** [comment]
Hola! ¿alguna noticia sobre nuevas credenciales de prueba?

**Comment by leosoto** [comment]
Hola! Una vez que https://github.com/TransbankDevelopers/transbank-sdk-java/pull/67 sea mezclado (allí puedes ver el nuevo certificado) y lancemos una nueva versión del SDK Java podremos actualizar este repo para que funcione :)

**Comment by paecasti** [comment]
> Hola! Una vez que [TransbankDevelopers/transbank-sdk-java#67](https://github.com/TransbankDevelopers/transbank-sdk-java/pull/67) sea mezclado (allí puedes ver el nuevo certificado) y lancemos una nueva versión del SDK Java podremos actualizar este repo para que funcione :)

Son unos grandes!

**Comment by leosoto** [comment]
Ahora solo estamos esperando que #2 aterrice en master y este ejemplo AhoraSiQueSiQueFuncionará®.

**Comment by leosoto** [comment]
Estamos listos con esto. Gracias @paecasti por el reporte original y el interés en PatPass-by-Webpay.
